### ISSUE TITLE
fix scaling

### ISSUE THREAD

**Issue by sakgoyal** [PhillipNgo/pScheduler#48] opened 2019-10-22 22:04 UTC
mobile scaling is awefull. needs to be fixed.

**Comment by PhillipNgo** [comment] 2019-10-23 00:46
Duplicate of #10. Mobile scaling wasn't the first thought when this was first built out so it's not the nicest - also the content would be hard to fit the size on the screen without a redesign. Any suggestions would be a nice (and a nicer way of making an issue)

**Closed as completed by PhillipNgo** 2019-10-23 00:46 UTC
Labels: duplicate
